---
title: "Data viz options"
author: "Clarissa Boyajian"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(vistime)
```

```{r parameters}
# html color codes
dark_green <- "#196F3D"
dark_yellow <- "#EBA61E"
dark_blue <- "#004266"
dark_red <- "#990000"
```


## Gantt period option:
```{r}
# create df
phase_timeline <- data.frame(
  phase = c("Proposal", 
           "Selection",
           "Capstone Project"),
  start_y = c(rep(c(2021), times = 2), 
              rep(c(2022), times = 1)),
  start_m = c(08, 11, 01),
  start_d = c(01, 01, 01),
  end_y = c(rep(c(2021), times = 2), 
            rep(c(2022), times = 1)),
  end_m = c(10, 12, 06),
  end_d = c(31, 31, 30)
  )

# add color for phases
phase_timeline <- phase_timeline %>% 
  mutate(phase_color = case_when(phase == "Proposal" ~ dark_green,
                                 phase == "Selection" ~ dark_blue,
                                 phase == "Capstone Project" ~ dark_red))

# create start date column
phase_timeline$start_date <- with(phase_timeline, 
                                  ymd(sprintf('%04d%02d%02d', 
                                      phase_timeline$start_y, 
                                      phase_timeline$start_m, 
                                      phase_timeline$start_d)))

# create end date column
phase_timeline$end_date <- with(phase_timeline, 
                                ymd(sprintf('%04d%02d%02d', 
                                      phase_timeline$end_y, 
                                      phase_timeline$end_m, 
                                      phase_timeline$end_d)))

# plot viz
phase_plot <- gg_vistime(data = phase_timeline,
           col.event = "phase",
           col.start = "start_date",
           col.end = "end_date",
           col.color = "phase_color",
           optimize_y = TRUE,
           title = "Timeline of Capstone Phases") +
  theme_classic()

phase_plot

## 1 IDEA: we could add each item that occurs within each phase as a list that shows up when you hover over that phase (unsure how to do this)
```


## Point-line-segment events option:
```{r Create df}
# create df
cap_timeline <- data.frame(
  task = c("Capstone Kickoff\nWorkshop", 
           "Writing A Proposal\nWorkshop", 
           "Write\nProposal", 
           "Projects Revealed\nto MEDS", 
           "Student\nVoting", 
           "Final Capstone\nAssignments",
           "Design &\nImplementation Plan",
           "Design Plan\nPresentations",
           "Technical\nDocumentation & Repo",
           "Final\nPresentations"),
  event_type = c("Proposal (required)",
                 "Proposal (optional)",
                 "Proposal (optional)",
                 "Announcements",
                 "Proposal (required)",
                 "Announcements", 
                 "Capstone Project",
                 "Capstone Project",
                 "Capstone Project",
                 "Capstone Project"),
  start_y = c(rep(c(2021), times = 6), 
              rep(c(2022), times = 4)),
  start_m = c(08, 08, 08, 11, 11, 12, 01, 03, 03, 05),
  start_d = c(09, 26, 27, 17, 19, 01, 02, 03, 04, 26),
  end_y = c(rep(c(2021), times = 6), 
            rep(c(2022), times = 4)),
  end_m = c(08, 08, 10, 11, 11, 12, 02, 03, 04, 05),
  end_d = c(10, 27, 15, 18, 24, 02, 11, 04, 29, 27)
  )

# re-level event type factor and add color
event_type_levels <- c("Announcements", "Proposal (optional)", "Proposal (required)", "Capstone Project")
cap_timeline$event_type <- factor(cap_timeline$event_type, 
                                  levels = event_type_levels, 
                                  ordered = TRUE)
event_type_color <- (c(dark_yellow, dark_green, dark_blue, dark_red))

# create start date column
cap_timeline$start_date <- with(cap_timeline, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline$start_y, 
                                      cap_timeline$start_m, 
                                      cap_timeline$start_d)))

# create end date column
cap_timeline$end_date <- with(cap_timeline, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline$end_y, 
                                      cap_timeline$end_m, 
                                      cap_timeline$end_d)))

# create average date
cap_timeline <- cap_timeline %>% 
  mutate(middle_date = start_date + ((end_date - start_date) * 0.5))

# add numerical order row
cap_timeline$order <- 1:nrow(cap_timeline)

# order all rows by date
cap_timeline <- cap_timeline[with(cap_timeline, order(start_date)), ]

```

```{r}
month_buffer <- 2

# creating df for month ticks/labels
month_date_range <- seq(min(cap_timeline$middle_date) - months(month_buffer), 
                        max(cap_timeline$middle_date) + months(month_buffer), 
                        by = "month")
month_format <- format(month_date_range, "%b")
month_df <- data.frame(month_date_range, month_format)

# creating df for year labels
year_date_range <- seq(min(cap_timeline$middle_date) - months(month_buffer), 
                       max(cap_timeline$middle_date) + months(month_buffer), 
                       by = "year")
year_format <- format(year_date_range, "%Y")
year_df <- data.frame(year_date_range, year_format)

```

```{r}
# line and point locations
positions <- c(0.65, -0.25, 0.4, 0.25, -0.25, 
               0.65, -0.35, 0.4, -0.25, 0.65)

directions <- c(1, -1, 1, 1, -1, 
                1, -1, 1, -1, 1)

line_pos <- data.frame(
  "middle_date" = unique(cap_timeline$middle_date),
  "position" = rep(positions, length.out = length(unique(cap_timeline$middle_date))),
  "direction" = rep(directions, length.out = length(unique(cap_timeline$middle_date)))
)

cap_timeline <- left_join(x = cap_timeline, y = line_pos, by = "middle_date")
```

```{r}
text_offset <- 0.125

absolute_value <- (abs(cap_timeline$position))

text_position <- absolute_value + text_offset

cap_timeline$text_position <- text_position * cap_timeline$direction
```

```{r Create timeline plot}
timeline_plot <- ggplot(data = cap_timeline, 
                        aes(x = middle_date, 
                            y = position, 
                            col = event_type, 
                            label = task)) +
  labs(col = "Tasks") +
  scale_color_manual(values = event_type_color, 
                     labels = event_type_levels, 
                     drop = FALSE) +
  theme_classic() +
  geom_hline(yintercept = 0, 
             color = "black", 
             size = 0.3) +
  geom_segment(aes(y = position,
                   yend = 0,
                   xend = middle_date), 
               color = "black", 
               size = 0.2) +
  geom_point(aes(y = position), 
             size = 3) +
  theme(axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        legend.position = "bottom") +
  geom_text(data = month_df, 
            aes(x = month_date_range,
                y = -0.15,
                label = month_format), 
            size = 3.5, 
            vjust = 0.5, 
            color = "black", 
            angle = 90) +
  geom_text(data = year_df,
            aes(x = year_date_range,
                y = -0.5,
                label = year_format,
                fontface = "bold"), 
            size = 3.5, 
            color = "black") +
  geom_text(aes(y = text_position, 
                label = task), 
            size = 3.5, 
            vjust = 0.6) +
  ggtitle("Timeline of Capstone Milestones")

timeline_plot
```

```{r}
ggsave(plot = phase_plot, filename = "phase_plot.png", height = 10, width = 12) ## need to figure out how to remove the extre space above and below on y-axis

ggsave(plot = timeline_plot, filename = "timeline_plot.png", height = 10, width = 12)
```









