---
title: "Data viz (gant chart)"
author: "Clarissa Boyajian"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(vistime)
```


```{r Create df}
cap_timeline <- data.frame(
  task = c("Capstone Kickoff Workshop", 
           "Writing A Proposal Workshop", 
           "Write Proposals", 
           "Projects Revealed to MEDS", 
           "Student Voting", 
           "Final Capstone Assignments",
           "Design & Implementation Plan",
           "Design Plan Presentations",
           "Technical Documentation & Repo",
           "Final Presentations"),
  event_type = factor(c("Proposal (required)", 
                 "Proposal (optional)",
                 "Proposal (optional)",
                 "Announcements", 
                 "Proposal (required)", 
                 "Announcements", 
                 "Capstone Project",
                 "Capstone Project",
                 "Capstone Project",
                 "Capstone Project"),
                 levels = c("Announcements", "Proposal (optional)", "Proposal (required)", "Capstone Project"),
                 ordered = TRUE),
  start_y = c(rep(c(2021), times = 6), 
              rep(c(2022), times = 4)),
  start_m = c(08, 08, 08, 11, 11, 12, 01, 03, 03, 05),
  start_d = c(09, 26, 27, 17, 19, 01, 02, 03, 04, 26),
  end_y = c(rep(c(2021), times = 6), 
            rep(c(2022), times = 4)),
  end_m = c(08, 08, 10, 11, 11, 12, 02, 03, 04, 05),
  end_d = c(10, 27, 15, 18, 24, 02, 11, 04, 29, 27)
  )

cap_timeline$start_date <- with(cap_timeline, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline$start_y, 
                                      cap_timeline$start_m, 
                                      cap_timeline$start_d)))

cap_timeline$end_date <- with(cap_timeline, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline$end_y, 
                                      cap_timeline$end_m, 
                                      cap_timeline$end_d)))

cap_timeline$order <- 1:nrow(cap_timeline)

cap_timeline <- cap_timeline[with(cap_timeline, order(start_date)), ]
```



```{r Attempt 1: geom_segment, fig.width=9}
timeline_viz <- cap_timeline %>% 
 ggplot(aes(x = start_date, 
            y = order, 
            color = event_type)) +
 geom_segment(aes(xend = end_date, 
                  yend = order, 
                  color =  event_type), 
              size = 10,
              show.legend = TRUE) +
 geom_text(aes(label = task), 
           size = 4, 
           show.legend = FALSE, 
           nudge_x = -55
           ) +
 scale_color_manual(values = c("Proposal (optional)" = "#004266", 
                               "Announcements" = "#FCB322", 
                               "Proposal (required)" = "#D22B2B",
                               "Capstone Project" = "darkred")) + 
  expand_limits(x = as.Date(c("2021-04-01", "2022-06-30"))) +
  theme(legend.title = element_blank(),
        legend.direction = "vertical",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(),
        text = element_text(size = 15),
        panel.background = element_rect("white"),
        panel.border = element_rect(fill = NA),
        panel.grid = element_line(NA)) +
  scale_x_continuous(breaks = as.Date(c("2021-08-01", "2021-09-01", "2021-10-01", "2021-11-01", "2021-12-01", 
                                        "2022-01-01", "2022-02-01", "2022-03-01", "2022-04-01", "2022-05-01")),
                     labels = c("Aug 2021", "Sept", "Oct", "Nov", "Dec", "Jan 2022", "Feb", "March", "April", "May")) +
  labs(title = "MEDS Capstone Timeline")

timeline_viz
```


```{r Attempt 2: vistime}
test_df <- cap_timeline %>% 
  select("task", "event_type", "start_date", "end_date") %>% 
  mutate(event_type_color = case_when(event_type == "Proposal (optional)" ~ "#004266",
                                      event_type == "Announcements" ~ "goldenrod",
                                      event_type == "Proposal (required)" ~ "#990000",
                                      event_type == "Capstone Project" ~ "darkred"))

fct_relevel(test_df$event_type, "Capstone Project", after = 3)

test_plot <- vistime(test_df,
                col.event = "task",
                col.start = "start_date",
                col.end = "end_date",
                col.color = "event_type_color",
                optimize_y = TRUE,
                linewidth = 50,
                title = "MEDS Capstone Proposal Timeline")

test_plot
```


```{r Attempt 3: gg_vistime, eval=FALSE}
test_df_2 <- cap_timeline %>% 
  select("task", "event_type", "start_date", "end_date") %>% 
  mutate(event_type_color = c("#D62828", "#004266", "#004266", "#D62828", "#FCB322", "#FCB322", "darkred", "darkred", "darkred", "darkred"))

test_plot2 <- gg_vistime(data = test_df_2,
                         col.event = "task",
                         col.start = "start_date",
                         col.end = "end_date",
                         col.color = "event_type_color",
                         optimize_y = TRUE)

test_plot2_df <- ggplot_build(test_plot2)

test_plot2_df$data[[4]]$hjust <- 90

test_plot2_rebuilt <- ggplot_gtable(test_plot2_df)

test_plot2
plot(test_plot2_rebuilt)
```

Halina attempt
```{r}
cap_timeline_hd <- data.frame(
  task = c("Capstone Kickoff Workshop", 
           "Writing A Proposal Workshop", 
           "Write Proposals", 
           "Projects Revealed to MEDS", 
           "Student Voting", 
           "Final Capstone Assignments",
           "Design & Implementation Plan",
           "Design Plan Presentations",
           "Technical Documentation & Repo",
           "Final Presentations"),
  start_y = c(rep(c(2021), times = 6), 
              rep(c(2022), times = 4)),
  start_m = c(08, 08, 08, 11, 11, 12, 01, 03, 03, 05),
  start_d = c(09, 26, 27, 17, 19, 01, 02, 03, 04, 26),
  end_y = c(rep(c(2021), times = 6), 
            rep(c(2022), times = 4)),
  end_m = c(08, 08, 10, 11, 11, 12, 02, 03, 04, 05),
  end_d = c(10, 27, 15, 18, 24, 02, 11, 04, 29, 27)
  )

cap_timeline_hd$start_date <- with(cap_timeline_hd, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline_hd$start_y, 
                                      cap_timeline_hd$start_m, 
                                      cap_timeline_hd$start_d)))

cap_timeline_hd$end_date <- with(cap_timeline_hd, 
                          ymd(sprintf('%04d%02d%02d', 
                                      cap_timeline_hd$end_y, 
                                      cap_timeline_hd$end_m, 
                                      cap_timeline_hd$end_d)))

cap_timeline_hd$order <- 1:nrow(cap_timeline_hd)

cap_timeline_hd <- cap_timeline_hd[with(cap_timeline_hd, order(start_date)), ]
```

```{r}
specific_timeline_hd <- cap_timeline_hd %>% 
  select("task", "start_date", "end_date") %>% 
  mutate(event_type_color = c("#D62828", "#004266", "#004266", "#D62828", "#FCB322", "#FCB322", "darkred", "darkred", "darkred", "darkred"))
```

```{r}
phase_timeline_hd <- data.frame(
  phase = c("Proposal", 
           "Selection",
           "Capstone Project"),
  start_y = c(rep(c(2021), times = 2), 
              rep(c(2022), times = 1)),
  start_m = c(08, 11, 01),
  start_d = c(01, 01, 01),
  end_y = c(rep(c(2021), times = 2), 
            rep(c(2022), times = 1)),
  end_m = c(10, 12, 06),
  end_d = c(31, 31, 30)
  )

phase_timeline_hd$start_date <- with(phase_timeline_hd, 
                          ymd(sprintf('%04d%02d%02d', 
                                      phase_timeline_hd$start_y, 
                                      phase_timeline_hd$start_m, 
                                      phase_timeline_hd$start_d)))

phase_timeline_hd$end_date <- with(phase_timeline_hd, 
                          ymd(sprintf('%04d%02d%02d', 
                                      phase_timeline_hd$end_y, 
                                      phase_timeline_hd$end_m, 
                                      phase_timeline_hd$end_d)))

phase_timeline_hd$order <- 1:nrow(phase_timeline_hd)

phase_timeline_hd <- phase_timeline_hd[with(phase_timeline_hd, order(start_date)), ]
```

```{r}
phase_timeline_hd_2 <- phase_timeline_hd %>% 
  select("phase", "start_date", "end_date") %>% 
  mutate(event_type_color = c("#D62828", "#004266", "darkred"))
```

```{r}
gg_vistime(data = phase_timeline_hd_2,
           col.event = "phase",
           col.start = "start_date",
           col.end = "end_date",
           col.color = "event_type_color",
           optimize_y = TRUE)
```

